name: CI

on: [push, pull_request]

jobs:
  ci:
    name: Continuous integration
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Cache dependencies
        uses: actions/cache@v2
        id: cache
        with:
          path: ./node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ runner.os }}-yarn-

      - name: Install dependencies
        run: yarn install

      - name: Test
        run: yarn test a

      - name: Build
        run: yarn build

      - name: Start
        run: yarn start
